
apiVersion: v1
kind: Service
metadata:
  name: test-api
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: api
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: europe-west4-docker.pkg.dev/supy-development-400307/test/test-api-test:5c4f8b218
        # env:
        # - name: CS_DB_HOST
        #   value: mysql
        # - name: CS_DB_NAME
        #   value: mydb
        # - name: CS_DB_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: cs-db-pass
        #       key: db-pass
        ports:
        - containerPort: 5000

